#    This file is part of darktable.
#    copyright (c) 2016-2020 Roman Lebedev.
#
#    darktable is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    darktable is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with darktable.  If not, see <http://www.gnu.org/licenses/>.

notifications:
  irc:
    channels:
#     - "chat.freenode.net#darktable"
      - secure: "fCQRwV2kMc5ycWjuuim0q+u9DS8D64oIWpfDipvrJDcIsS+MfkfkKrF68kDhNbDNtZHUfvP2Se/0hxUWw825VnyzNZZImrK+giOIGS588apxBPzNY3YMWMzwc4RaCKfyOWvFZDRGJwFzAwPWdSSQh7KMGJj7VibgoyhDTSSJYAk="
    skip_join: true
    template:
      - "%{repository}#%{build_number} (\x037%{branch}\x03 - \x02%{commit}\x02 : \x033%{author}\x03): \x1f\x02%{message}\x02\x1f"
      - "Build details : <%{build_url}>"
  email:
    recipients:
#     - darktable-ci@lists.darktable.org
      - secure: "Fvo7jlL8jpV+asdCmHHeJUK4BYw1JQvAxFpKUPZ/FWjkBfZ3W6is8jRBJVGfnt9TTvD1W2vsaLqeClv1SUfYw0t0keRSP0+0TB5R9ULIfC6/3bFLmp2aDPhBHLRjH3byxiJ46PvADcZ7MC+6jtf0YEEqy6uLbjaX4PiIXINM7Bo="
    on_success: always
    on_failure: always

language: c

dist: focal

env:
  global:
    - SRC_DIR=$TRAVIS_BUILD_DIR
    - BUILD_DIR="$SRC_DIR/build"
    - INSTALL_PREFIX="$SRC_DIR/install"
    - CFLAGS=-pipe CXXFLAGS=-pipe
    - CMAKE_BUILD_TYPE="RelWithDebInfo"
    - GENERATOR="Ninja"
    - TARGET=build

jobs:
 fast_finish: true
 include:
  - name: "Linux Clang10"
    os: linux
    compiler: clang
    addons:
      apt:
        sources:
          - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main'
            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
          - clang-10
          - libc++-10-dev
          - libomp-10-dev
          - libclang-common-10-dev
          - llvm-10-dev
    env: CC=clang-10 CXX=clang++-10
  - name: "Linux GCC 9"
    os: linux
    compiler: gcc
  - name: "Linux GCC9 Release Build"
    os: linux
    compiler: gcc
    env:
      - CMAKE_BUILD_TYPE="Release"
  - name: "Linux GCC9 Debug Build"
    os: linux
    compiler: gcc
    env:
      - TARGET=skiptest
      - CMAKE_BUILD_TYPE="Debug"
  - name: "GCC9 Disabled all features"
    os: linux
    compiler: gcc
    env: 
      - TARGET=nofeatures
  - name: "Usermanual"
    os: linux
    dist: bionic
    compiler: gcc
    env: TARGET=usermanual CXX=g++-9 CC=gcc-9 # EXTRA_TMPFS="--tmpfs /tmp"
    addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-9
            - g++-9
    install: 
      - sudo add-apt-repository -y universe
      - sudo add-apt-repository -y multiverse
      - sudo apt-get update
      - sudo apt-get -y install default-jdk-headless default-jre-headless
      - sudo apt-get -y install docbook docbook-xml docbook-xsl docbook-xsl-saxon
      - sudo apt-get -y install fop gnome-doc-utils imagemagick libsaxon-java xsltproc

addons:
  apt:
    update: true

before_install:
- |-
  sudo apt-get install \
    appstream-util \
    desktop-file-utils \
    gettext \
    git \
    intltool \
    libatk1.0-dev \
    libcairo2-dev \
    libcolord-dev \
    libcolord-gtk-dev \
    libcmocka-dev \
    libcups2-dev \
    libcurl4-gnutls-dev \
    libexiv2-dev \
    libflickcurl-dev \
    libgdk-pixbuf2.0-dev \
    libglib2.0-dev \
    libgphoto2-dev \
    libgraphicsmagick1-dev \
    libgtk-3-dev \
    libjpeg-dev \
    libjson-glib-dev \
    liblcms2-dev \
    liblensfun-dev \
    liblua5.2-dev \
    liblua5.3-dev \
    libopenexr-dev \
    libopenjp2-7-dev \
    libosmgpsmap-1.0-dev \
    libpango1.0-dev \
    libpng-dev \
    libpugixml-dev \
    librsvg2-dev \
    libsaxon-java \
    libsecret-1-dev \
    libsoup2.4-dev \
    libsqlite3-dev \
    libtiff5-dev \
    libwebp-dev \
    libx11-dev \
    libxml2-dev \
    libxml2-utils \
    ninja-build \
    perl \
    po4a \
    python3-jsonschema \
    xsltproc \
    zlib1g-dev;

script:
- |-
  mkdir "$BUILD_DIR";
  mkdir "$INSTALL_PREFIX";
  "$SRC_DIR/.ci/ci-script.sh";