language: c

before_install:

  - sudo apt-get install intltool libatk1.0-dev libcairo2-dev libsoup2.4-dev
    libexiv2-dev libfontconfig1-dev libfreetype6-dev libgomp1 libgtk2.0-dev
    libjpeg-dev libtiff4-dev liblcms2-dev liblensfun-dev libpng12-dev
    libsqlite3-dev libstdc++6-4.4-dev libxml2-dev libopenexr-dev
    libcurl4-gnutls-dev libgphoto2-2-dev libdbus-glib-1-dev
    libgnome-keyring-dev fop librsvg2-dev libflickcurl-dev cmake liblua5.2-dev
    libcolord-dev libjson-glib-dev libgtk-3-dev

script:

  - ./build.sh

notifications:
  email: false
