#    This file is part of darktable.
#    copyright (c) 2016 Roman Lebedev.
#
#    darktable is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    darktable is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with darktable.  If not, see <http://www.gnu.org/licenses/>.

sudo: required

notifications:
  irc:
    channels:
#     - "chat.freenode.net#darktable"
      - secure: "fCQRwV2kMc5ycWjuuim0q+u9DS8D64oIWpfDipvrJDcIsS+MfkfkKrF68kDhNbDNtZHUfvP2Se/0hxUWw825VnyzNZZImrK+giOIGS588apxBPzNY3YMWMzwc4RaCKfyOWvFZDRGJwFzAwPWdSSQh7KMGJj7VibgoyhDTSSJYAk="
    skip_join: true
    template:
      - "%{repository}#%{build_number} (\x037%{branch}\x03 - \x02%{commit}\x02 : \x033%{author}\x03): \x1f\x02%{message}\x02\x1f"
      - "Build details : %{build_url}"
  email:
    recipients:
#     - darktable-ci@lists.darktable.org
      - secure: "Fvo7jlL8jpV+asdCmHHeJUK4BYw1JQvAxFpKUPZ/FWjkBfZ3W6is8jRBJVGfnt9TTvD1W2vsaLqeClv1SUfYw0t0keRSP0+0TB5R9ULIfC6/3bFLmp2aDPhBHLRjH3byxiJ46PvADcZ7MC+6jtf0YEEqy6uLbjaX4PiIXINM7Bo="
    on_success: always
    on_failure: always

services:
  - docker

before_install:
#  - docker build -t darktable/darktable .
  - docker pull darktable/darktable

env:
  global:
    - SRC_DIR=/build/darktable
    - BUILD_DIR=/build/darktable-build
    - INSTALL_PREFIX=/build/darktable-install
    - CFLAGS=-pipe CXXFLAGS=-pipe
  matrix:
    - CC=gcc CXX=g++ TARGET=build
    - CC=clang-3.8 CXX=clang++-3.8 TARGET=build
    - CC=gcc CXX=g++ TARGET=usermanual # EXTRA_TMPFS="--tmpfs /tmp"

matrix:
  fast_finish: true

script:
  - docker run --read-only --volume $TRAVIS_BUILD_DIR:$SRC_DIR:ro --tmpfs $BUILD_DIR --workdir $BUILD_DIR --tmpfs $INSTALL_PREFIX $EXTRA_TMPFS --env CC --env CXX --env CFLAGS --env CXXFLAGS --env SRC_DIR --env BUILD_DIR --env INSTALL_PREFIX --env TARGET darktable/darktable sh -c "$SRC_DIR/ci-script.sh"
