language: c

env:
  global:
    - SRC_DIR="$TRAVIS_BUILD_DIR"
    - BUILD_DIR="$SRC_DIR/build"
    - INSTALL_PREFIX="$SRC_DIR/install"
    - CFLAGS=-pipe CXXFLAGS=-pipe
    - CMAKE_BUILD_TYPE="RelWithDebInfo"
    - GENERATOR="Ninja"
    - TARGET=build

jobs:
 fast_finish: true
 include:
  - os: windows
    compiler: clang
    compiler:
      - clang
      - gcc
    env: 
      - GENERATOR="MSYS Makefiles"
      - CC=clang CXX=clang++

before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd'
        export msys2+='& set MSYS=winsymlinks:nativestrict'
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -full-path -here -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed base-devel
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-clang
        $msys2 pacman -Ql mingw-w64-x86_64-clang
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-cmake
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-nsis
        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        $msys2 pacman -S --needed --noconfirm  mingw-w64-x86_64-{exiv2,lcms2,dbus-glib,openexr,sqlite3,libxslt,libsoup,libavif,libwebp,libsecret,lua,graphicsmagick,openjpeg2,gtk3,pugixml,libexif,osm-gps-map,libgphoto2,flickcurl,drmingw,gettext,python3,iso-codes}
        $msys2 pacman -S --needed --noconfirm mingw-w64-x86_64-openmp
        ## taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export PATH=/mingw64/bin:$PATH
        ## export MAKE=mingw32-make  # so that Autotools can find it
        ;;
    esac

before_cache:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

cache:
  directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64

script:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        $msys2 mkdir "$BUILD_DIR";
        $msys2 mkdir "$INSTALL_PREFIX";
        $msys2 "$SRC_DIR/.ci/ci-script.sh";
        ;;
    esac
