name: Nightly Macos PKG
# TODO: move to nightly.yml after finalizing here.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macOS:
    name: macOS.${{ matrix.compiler.compiler }}.${{ matrix.target }}
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        compiler:
          - { compiler: XCode,   CC: cc, CXX: c++ }
        btype: [ Release ]
        target:
          - skiptest
    env:
      CC: ${{ matrix.compiler.CC }}
      CXX: ${{ matrix.compiler.CXX }}
      SRC_DIR: ${{ github.workspace }}/src
      BUILD_DIR: ${{ github.workspace }}/build
      INSTALL_PREFIX: ${{ github.workspace }}/install
      CMAKE_BUILD_TYPE: ${{ matrix.btype }}
      GENERATOR: Ninja
      TARGET: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          path: src
      - name: Install MacportsCI
        run: |
          curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
          source ./macports-ci install
          #sudo echo "buildfromsource always" >> /opt/local/etc/macports/macports.conf
          #sudo echo "macosx_deployment_target 10.7" >> /opt/local/etc/macports/macports.conf
          #sudo echo "cxx_stdlib libc++" >> /opt/local/etc/macports/macports.conf
          echo "+no_gnome +no_x11 +quartz -x11 -gnome" | sudo tee -a /opt/local/etc/macports/variants.conf
          mkdir -p ~/ports/devel/gnutls/files \
                   ~/ports/lang/python37/files \
                   ~/ports/lang/python38/files \
                   ~/ports/graphics/GraphicsMagick/files \
                   ~/ports/graphics/ImageMagick/files \
                   ~/ports/textproc \
                   ~/ports/science
          cp -R "$(port dir gnutls)" ~/ports/devel
          curl -Lo ~/ports/devel/gnutls/files/patch.diff https://raw.github.com/darktable-org/darktable/master/packaging/macosx/gnutls-disable-connectx.diff
          cp -R "$(port dir python37)" ~/ports/lang
          curl -Lo ~/ports/lang/python37/files/patch.diff https://raw.github.com/darktable-org/darktable/master/packaging/macosx/python36-stack_size.diff
          cp -R "$(port dir python38)" ~/ports/lang
          curl -Lo ~/ports/lang/python38/files/patch.diff https://raw.github.com/darktable-org/darktable/master/packaging/macosx/python38-stack_size.diff
          cp -R "$(port dir GraphicsMagick)" ~/ports/graphics
          curl -Lo ~/ports/graphics/GraphicsMagick/files/patch.diff https://raw.github.com/darktable-org/darktable/master/packaging/macosx/gm-deployment_target.diff
          cp -R "$(port dir ImageMagick)" ~/ports/graphics
          curl -Lo ~/ports/graphics/ImageMagick/files/patch.diff https://raw.github.com/darktable-org/darktable/master/packaging/macosx/im-stdlib.diff
          echo "patchfiles-append patch.diff" >> ~/ports/devel/gnutls/Portfile
          echo "patchfiles-append patch.diff" >> ~/ports/lang/python37/Portfile
          echo "patchfiles-append patch.diff" >> ~/ports/lang/python38/Portfile
          echo "patchfiles-append patch.diff" >> ~/ports/graphics/GraphicsMagick/Portfile
          echo "patchfiles-append patch.diff" >> ~/ports/graphics/ImageMagick/Portfile
          cp -R "$(port dir pugixml)" ~/ports/textproc
          curl -L https://raw.github.com/darktable-org/darktable/master/packaging/macosx/pugixml-stdlib.patch | patch -d ~/ports -p0
          cp -R "$(port dir librsvg)" ~/ports/graphics
          curl -L https://raw.github.com/darktable-org/darktable/master/packaging/macosx/librsvg-nocargo.patch | patch -d ~/ports -p0
          cp -R "$(port dir gmic)" ~/ports/science
          curl -L https://raw.github.com/darktable-org/darktable/master/packaging/macosx/gmic-minimal.patch | patch -d ~/ports -p0
          sudo portindex ~/ports
          source ./macports-ci localports ~/ports
          sudo port install git exiv2 libgphoto2 gtk-osx-application-gtk3 lensfun librsvg libsoup openexr json-glib flickcurl GraphicsMagick openjpeg lua webp libsecret pugixml osm-gps-map adwaita-icon-theme tango-icon-theme intltool iso-codes libomp gmic
      - name: macports log upload
        if: ${{ failure() }}
        uses: 'actions/upload-artifact@v2'
        with:
          name: macports_logs.${{ github.sha }}
          path: /opt/local/var/macports/logs/*/*/main.log
          retention-days: 1
      - name: Build and Install
        run: |
          cmake -E make_directory "${BUILD_DIR}";
          cmake -E make_directory "${INSTALL_PREFIX}";
          cd "${BUILD_DIR}"
          cmake "${SRC_DIR}" \
            -DCMAKE_BUILD_TYPE="$CMAKE_BUILD_TYPE" \
            -DCMAKE_CXX_FLAGS=-stdlib=libc++ \
            -DOpenMP_C_INCLUDE_DIR=/opt/local/include/libomp \
            -DOpenMP_CXX_INCLUDE_DIR=/opt/local/include/libomp \
            -DCMAKE_LIBRARY_PATH=/opt/local/lib/libomp \
            -DBINARY_PACKAGE_BUILD=ON \
            -DRAWSPEED_ENABLE_LTO=ON \
            -DBUILD_CURVE_TOOLS=ON \
            -DBUILD_NOISE_TOOLS=ON
          make
          sudo make install